import { GoogleGenAI } from '@google/genai';
import { logAuditEvent } from '@/lib/agents/audit';
import { requireEnv } from '@/lib/env';
import { sendEmail } from '@/lib/integrations/gmail';
import { getServiceClient } from '@/lib/supabase';

interface ReportTask {
  task: string;
  project: string | null;
  status: string;
  due_date: string | null;
}

export type WeeklyReportResult =
  | { status: 'sent'; rag: string }
  | { status: 'no_tasks' }
  | { status: 'task_load_failed' }
  | { status: 'send_failed' };

function getAiClient() {
  return new GoogleGenAI({ apiKey: requireEnv('GEMINI_API_KEY') });
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function getRag(tasks: ReportTask[]) {
  const blocked = tasks.filter((task) => task.status === 'blocked').length;
  const overdue = tasks.filter((task) => task.due_date && new Date(task.due_date) < new Date() && task.status === 'pending').length;

  if (blocked >= 3 || overdue >= 3) return '🔴 RED';
  if (overdue >= 1) return '🟡 AMBER';
  return '🟢 GREEN';
}

function groupByProject(tasks: ReportTask[]) {
  return tasks.reduce<Record<string, ReportTask[]>>((acc, task) => {
    const project = task.project ?? 'No Project';
    acc[project] = acc[project] ?? [];
    acc[project].push(task);
    return acc;
  }, {});
}

export async function sendWeeklyReportEmail(opts: { requestor: string }): Promise<WeeklyReportResult> {
  const sb = getServiceClient();
  const weekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

  const { data: tasks, error } = await sb
    .from('tasks')
    .select('task, project, status, due_date')
    .gte('updated_at', weekAgo)
    .order('project', { ascending: true });

  if (error) return { status: 'task_load_failed' };
  if (!tasks || tasks.length === 0) return { status: 'no_tasks' };

  const typedTasks = tasks as ReportTask[];
  const grouped = groupByProject(typedTasks);
  const rag = getRag(typedTasks);
  const response = await getAiClient().models.generateContent({
    model: 'gemini-2.5-flash',
    contents: `Status: ${rag}\nThis week's tasks:\n${JSON.stringify(grouped, null, 2)}\n\nWrite the executive narrative.`,
    config: {
      systemInstruction: 'You are a PMO assistant. Write a concise weekly status report in English. Use formal but warm tone. Max 200 words. Highlight wins, risks, and next steps.',
      temperature: 0.4,
      maxOutputTokens: 800,
    },
  });

  const narrative = response.text ?? '';
  const htmlBody = `
    <h1 style="color:#0F1E3D;font-family:Arial">Weekly PMO Status — ${new Date().toLocaleDateString('id-ID')}</h1>
    <p style="font-size:18px"><strong>Overall: ${rag}</strong></p>
    <div style="white-space:pre-wrap;font-family:Arial">${escapeHtml(narrative)}</div>
    <hr/>
    <h3 style="color:#0F1E3D">Task Detail</h3>
    ${Object.entries(grouped).map(([project, items]) => `
      <h4>${escapeHtml(project)}</h4>
      <ul>${items.map((task) => `<li>${escapeHtml(task.task)} — <em>${escapeHtml(task.status)}</em></li>`).join('')}</ul>
    `).join('')}
    <p style="font-size:11px;color:#999">Generated by PMO Pulse on TRAE.</p>
  `;

  const stakeholderEmails = (process.env.REPORT_RECIPIENTS || 'stakeholder@example.com')
    .split(',')
    .map((email) => email.trim())
    .filter(Boolean);

  const ragEnglish = rag.replace(/^[^A-Z]+\s*/, '');

  try {
    await sendEmail({ to: stakeholderEmails, subject: `Weekly PMO Status - ${ragEnglish}`, htmlBody });
    await logAuditEvent({ event_type: 'report_sent', actor_phone: opts.requestor, payload: { recipients: stakeholderEmails, rag } });
    return { status: 'sent', rag };
  } catch (err) {
    console.error('Report send failed:', err);
    return { status: 'send_failed' };
  }
}

